### ISSUE TITLE
Creating CI records

### ISSUE THREAD

**Issue by ccrossen** [Snow-Shell/servicenow-powershell#109]
I see there's a Get-ServiceNowConfigurationItem cmdlet, but no New-ServiceNowConfigurationItem cmdlet. Any chance it's on the ToDo list? Would be quite helpful. Thanks!

**Comment by BristleBeard** [comment]
Would this enhancement be upcoming in the near future?

**Comment by gdbarron** [comment]
Hi @BristleBeard, I can start looking at this.  Do you have a suggestion as to a base set of ci field values the function should accept?

**Comment by gdbarron** [comment]
if you wanted to get started now, you can always use `New-ServiceNowRecord -Table cmdb_ci -Values @{'field'='value'}`

**Comment by gdbarron** [comment]
I went ahead with a base set of fields.  You can always use `-CustomField` or let me know which fields are used most often and I can add them as properties.
