### ISSUE TITLE
Invoke-RestMethod : The remote server returned an error: (401) Unauthorized.

### ISSUE THREAD

**Issue by ScubaAlex-WPG** [Snow-Shell/servicenow-powershell#111]
Our Organization uses SSO login for Servicenow. I am getting a 401 error when providing valid credentials. Is there any way the script can log in by providing the domain credentials? I tried with a local servicenow account and works fine. But need to use a user under SSO

**Comment by brunobml** [comment]
I am having the same problem

**Comment by gdbarron** [comment]
Hi @ScubaAlex-WPG and @brunobml.  In doing some research, it doesn't look as if the API supports SSO.  Have you seen otherwise?

**Comment by gdbarron** [comment]
According to [this](https://docs.servicenow.com/bundle/quebec-application-development/page/integrate/inbound-rest/concept/c_RESTAPI.html#d955432e531) it's not supported.  If you find otherwise, please feel free to reopen the issue.
