### ISSUE TITLE
Update-ServiceNowNumber Issue

### ISSUE THREAD

**Issue by tosso91** [Snow-Shell/servicenow-powershell#112]
When trying to update a service now sc_task with this function, it fails when trying to add the "assigned_to" field. 

Cannot process argument transformation on parameter 'AssignedTo'. Cannot convert the %sysID of user% value of type "System.String" to type "System.Management.Automation.ParameterAttribute".

When using Update-ServiceNowTableEntry, I can pass the value assigned_to with no problems.

**Comment by Rick-2CA** [comment]
I'm able to run Update-ServiceNowNumber with -Values @{assigned_to='FirstName LastName'} and with -Values @{assigned_to='MySysId'} successfully.  The code under the hood for ServiceNowNumber and ServiceNowTableEntry are exactly the same for the Values parameter.

**Comment by gdbarron** [comment]
Hi @tosso91.  Is this still an issue?
