### ISSUE TITLE
3rd party idp Oauth support

### ISSUE THREAD

**Issue by Grummle** [Snow-Shell/servicenow-powershell#139]
All of the Oauth appears to be around Service Now being the idp correct? It looks to me like there is no support for a 3rd party like Azure Active Directory to act as the token provider. I have this setup in our SNOW instance, but if I can avoid writing a bunch of code you've already done I'm all for being lazy.

Just trying to make sure I've got it right before I start digging on how to get it to work with ours.

**Comment by Grummle** [comment]
I'm an idiot

.PARAMETER AccessToken
Provide the access token directly if obtained outside of this module.

**Comment by gdbarron** [comment]
Nah, happens to all of us :)
