### ISSUE TITLE
SSO Accounts are not supported 

### ISSUE THREAD

**Issue by noaboa97** [Snow-Shell/servicenow-powershell#157]
what also would be nice to mention, that due to the nature of SN it won’t allow SSO accounts to login.

**Comment by gdbarron** [comment]
Hi @noaboa97.  The api doesn't support sso.  Is there something specific you had in mind?

**Comment by noaboa97** [comment]
Yes, mention that in the reademe file.

I researched a bit and apparently it is possible over OAuth but I have to test it. Do you know if OAuth works with SSO Accounts?

**Comment by gdbarron** [comment]
Note added to readme, thanks for suggestion.

I've read it works with oauth2, but never setup it up myself.  Let me know how it goes.
