### ISSUE TITLE
Is there a way to find/edit "Test Items" within ServiceNow?

### ISSUE THREAD

**Issue by wwwb0n3zcom** [Snow-Shell/servicenow-powershell#195]
Is there a way to find/edit "Test Items" within ServiceNow?

Thank you,

-b0n3z

![image](https://user-images.githubusercontent.com/30855940/178321850-0fb88f17-6171-481a-b25f-b4be269a51af.png)

**Comment by gdbarron** [comment]
I'm not familiar with Test Items specifically, but if you right click on the item, select 'Copy URL to Clipboard' and then inspect it, that might give you a clue as to where the data lives.

It's most likely of the format `https://instance.service-now.com/nav_to.do?uri=<table>.do?sys_id=<sys_id>`.  If so, you can then use `Get-ServiceNowRecord -Table <table>` to query the table or `Get-ServiceNowRecord -Table <table> -ID <sys_id>` to get the specific item.

To edit, you would use `Update-ServiceNowRecord -Table <table> -ID <sys_id> -Values @{'field'='updated_value'}`.

**Comment by gdbarron** [comment]
@wwwb0n3zcom, did the above help?
