### ISSUE TITLE
Add Support For Change Management APIs

### ISSUE THREAD

**Issue by SolidOceanTrust** [Snow-Shell/servicenow-powershell#197]
Hello 👋 !
First, I'd like to say Thank You for such an awesome module!!

I have a few use-cases where I need to interact with the ServiceNow "Change Management" `/sn_chg_rest`  endpoints.
I have a working branch which implements this (in limited capacity) but I wanted to see if there was a specific way that you would like to see this implemented.

If not, I'm happy to open a PR and continue the conversation there.

My use cases:

- Ability to create a new Change Management Record from an existing Change Template (by `SySID`)
- Ability to update Change Management Records and CTasks

Thank you very much.

**Comment by gdbarron** [comment]
Hey @SolidOceanTrust!  I like the idea of working through via a PR.  I look forward to seeing what you have done!  Thanks.

**Comment by chrisjeter** [comment]
I'd second this request! Being able to create changes off of the standard change templates within the module would be amazing!

**Comment by gdbarron** [comment]
@chrisjeter, is there any reason the sn_chg_rest endpoints must be used as opposed to posting to the change_request table?

**Comment by chrisjeter** [comment]
Perhaps not? I was hoping to make use of the standard change templates that
are available with those endpoints. The only documentation i've been able
to find for creating changes based off of those with the api is through
those ends points.

**Comment by SolidOceanTrust** [comment]
💯 agree with @chrisjeter
I had to extend the module to support the sn_chg_rest endpoints in order to
make a standard change from a template.

I am just a guy trying to automate some ServiceNow stuff. Certainly not an
expert.

I have been negligent about getting an PR put together. I will open one
soon.

**Comment by gdbarron** [comment]
I've always used this with no issues:

```New-ServiceNowRecord -table change_request -Values @{'short_description'='new change';'chg_model'='put_model_name_here';'description'='woohoo'}```.

You can certainly add any another values you want.  Not sure if there are any drawbacks to this approach vs the specific APIs.

**Comment by SolidOceanTrust** [comment]
Very interesting!!
When you say "model_name" is that the same thing as the sysID of the std
change?

Also, fantastic work on this module!! Really saved me some time!!

**Comment by gdbarron** [comment]
From my understanding, model name is the name of the change model, which I assumed you meant by template.

![image](https://user-images.githubusercontent.com/11862024/222914994-02476077-4db4-4d72-afb7-0edb130d64ea.png)

If you have rights, you can see which ones are setup for your instance by going to 'Change Models'.  I replaced the model name with the sysid and that worked as well.

**Comment by SolidOceanTrust** [comment]
🤯🤯🤯🤯🤯🤯

I certainly don't have that level of access to any of my ServiceNow
tenants, but I will ask an adult with the right access to test this.

Thank you Greg!!

**Comment by chrisjeter** [comment]
I think the change models are different fromt the change templates though, are't they? I'm reffering to these:
![change_template](https://user-images.githubusercontent.com/36321541/223163027-3e69139a-3552-444a-82db-eab958c8e32f.png)

**Comment by gdbarron** [comment]
@chrisjeter thanks for pointing this out, it's new to me!  According to ChatGPT these 2 are in fact different with the template being the simpler of the 2 and a model supporting workflows, etc.

The 2 fields in the change_request table which control a standard change are `type` and `std_change_producer_version`.  I was able to create a change from a standard change template with `New-ServiceNowRecord -table change_request -Values @{'type'='Standard';'std_change_producer_version'='a08e02ec47410200e90d87e8dee4905a'}`.

To get the sys_id value for std_change_producer_version you can either manually create a change and get the value from 

`Get-ServiceNowRecord -table change_request -ID CHGxxxxxxx -Property std_change_producer_version`

or

```
Get-ServiceNowRecord -table std_change_producer_version -Property name,sys_id
sys_id                           name
------                           ----
16c2273c47010200e90d87e8dee49006 Clear BGP sessions on a Cisco router - 1
923504cc47410200e90d87e8dee490e2 Reboot Windows Server - 1
a08e02ec47410200e90d87e8dee4905a Add network switch to datacenter cabinet - 1
deb8544047810200e90d87e8dee490af Decommission local office Domain Controller - 1
f1c8d15147810200e90d87e8dee490f9 Change VLAN on a Cisco switchport - 1
```

**Comment by chrisjeter** [comment]
@gdbarron,
     I played around with this today. This does indeed work! I had messed with it before trying to get it working and had failed. The missing piece was that type=standard still needed to be set along with std_change_producer_version. Thank you so much for the help and the great module!

**Comment by gdbarron** [comment]
#238
