### ISSUE TITLE
Discussions

### ISSUE THREAD

**Issue by stahler** [Snow-Shell/servicenow-powershell#199]
Curious why the [Discussions](https://github.com/Snow-Shell/servicenow-powershell/discussions/) was removed.  Any chance of bring that back, there was some good stuff in there.

**Comment by gdbarron** [comment]
Hi @stahler. I was hoping to combine discussions with issues to have one place for all the info. I meant to move the discussions over, but didn't get a chance yet. Unfortunately, there is no read only option for discussions.  For now, I've reopened discussions.

**Comment by stahler** [comment]
Great!  Appreciate your module immensely!
