### ISSUE TITLE
Attachment Download functionality is gone in New Get-ServiceNowAttachment

### ISSUE THREAD

**Issue by chathamdl** [Snow-Shell/servicenow-powershell#211]

**Comment by chathamdl** [comment]
I found the download_link value and was able to get it to work with invoke-webrequest.  Just had a brain fart for a moment.  You can close this unless you have a different plan for download.

**Comment by gdbarron** [comment]
This was done 1.5 years ago with the v3 release, https://github.com/Snow-Shell/servicenow-powershell/releases/tag/v3.0.  Use `Export-ServiceNowAttachment`.

**Comment by chathamdl** [comment]
thanks for the quick reply

**Comment by gdbarron** [comment]
Have a look at the changelog as much has changed since then!
