### ISSUE TITLE
Updating a Non-Catalog Request

### ISSUE THREAD

**Issue by gdbarron** [Snow-Shell/servicenow-powershell#229]
### Discussed in https://github.com/Snow-Shell/servicenow-powershell/discussions/228

<div type='discussions-op-text'>

<sup>Originally posted by **DrMarkX** January 10, 2023</sup>
Is there a way to update non-catalog requests? I've tried...
`Get-ServiceNowRecord -Table 'u_non_catalog_request' -ID NON0292380 | Update-ServiceNowRecord -Values @{work_notes = "Updated by PowerShell"}`
But that returns the error message: _Invoke-WebRequest : The remote server returned an error: (400) Bad Request._</div>

**Comment by gdbarron** [comment]
@DrMarkX, would you mind testing the fix?

**Comment by DrMarkX** [comment]
I'm now able to update a non-catalog request.

**Comment by gdbarron** [comment]
I just did some testing and custom tables don't have a sys_class_name property so Get-ServiceNowRecord isn't passing it on.  I'll make the update to account for it.
