### ISSUE TITLE
Supplying Servicenow API key along with Set-ServiceNowAuth

### ISSUE THREAD

**Issue by jwnelson4** [Snow-Shell/servicenow-powershell#23]
Great work and I'm looking at using this in my environment for incident automation especially.  In order to interface with Servicenow in my environment an API key in the header info is required.

Would it be possible to provide a way to input this as an optional parameter/argument as part of the Set-ServiceNowAuth?

**Comment by Rick-2CA** [comment]
PR #83 has been submitted dealing with OAuth support.  Please check it out to provide feedback as we work on reviewing it for merging.
