### ISSUE TITLE
Comments still reference deleted function Get-ServiceNowUser

### ISSUE THREAD

**Issue by jbalcorn** [Snow-Shell/servicenow-powershell#239]
New-ServiceNowIncident.ps1 still has Get-ServiceNowUser in the instructions.  Very confusing.

```
# sys_id of the caller of the incident (user Get-ServiceNowUser to retrieve this)
        [parameter(Mandatory)]
        [string] $Caller,
```

**Comment by gdbarron** [comment]
This is a carryover from the older days.  Folks shouldn't look in code for function help.  We need to have traditional builtin help provide this data.
