### ISSUE TITLE
Zero size files cause 'Bad Request' error

### ISSUE THREAD

**Issue by mhouston100** [Snow-Shell/servicenow-powershell#241]
# Environment

```
Operating System: Windows 10 
ServiceNow module version: 3.4.3
PowerShell version:
```

# Steps to reproduce

1. Create Session
2. Attach an empty file

# Screenshots

This is a really minor issue, I would hardly call it a bug however attempting to attach a zero size file fails. We were testing some solutions using the module and were creating different files on the fly to test and the result is a 400 'Bad Request' error.

Probably not a situation that would come up often but worth reporting.

**Comment by gdbarron** [comment]
Minor or not, I appreciate you reporting it!  This will be fixed in an upcoming release.
