### ISSUE TITLE
How do you add associated CIs to a Change record?

### ISSUE THREAD

**Issue by OldTimerJB** [Snow-Shell/servicenow-powershell#243]
I can create a change record and ctasks for it but cannot figure out how to add hundreds of Server Cis to affected CI list in the change ticket.  Does anyone have examples?
Also the new change record function doesn't return the new change number.  I have to query for it after its created.

**Comment by OldTimerJB** [comment]
With the help of ChatGPT I was able to figure this out using the below:
ChatGPT gave me this code:
New-ServiceNowRecord -Table "task_ci" -Fields @{
    "task" = $changeSysId
    "cmdb_ci" = $serverSysId
}
I was able to change it to this and it worked..
New-ServiceNowRecord -Table "task_ci" -InputData @{
    "task" = $changeSysId
    "ci_item" = $serverSysId
}

**Comment by gdbarron** [comment]
New-ServiceNowChangeRecord has an InputData parameter you can use directly when creating the change. Also, -PassThru is used to return the details of the new record.

**Comment by OldTimerJB** [comment]
Thanks the -PassThru switch was the only other thing I needed.  Appreciate it.
