### ISSUE TITLE
JSON Square Brackets Added to Array's First and Last Objects

### ISSUE THREAD

**Issue by tehfonz** [Snow-Shell/servicenow-powershell#260]
# Environment

```
Operating System: Windows Server 2016
ServiceNow module version: 4.0.3
PowerShell version: 5.1
```

# Steps to reproduce
```
$CIs = @('Server1', 'Server2')
$UpdateChangeRequestDetails = @{
	u_affected_ci_list = $CIs
}
Update-ServiceNowRecord -ID $CHG -InputData $UpdateChangeRequestDetails -Verbose
```

# Expected behavior
Field in ServiceNow should just be populated with `Server1` & `Server2`

# Actual behavior
Field in ServiceNow is populated with `[Server1` & `Server2]`

# Screenshots
![image](https://github.com/Snow-Shell/servicenow-powershell/assets/29791934/836d1c21-65d5-4d83-b6e7-7ab003a2c7ad)
![image](https://github.com/Snow-Shell/servicenow-powershell/assets/29791934/38ea3a88-530c-43c0-a349-64c36822f119)

Not sending an array and instead casting a single object as a string removes the brackets
```
[string]$CIs = 'Server1'
$UpdateChangeRequestDetails = @{
	u_affected_ci_list = $CIs
}
Update-ServiceNowRecord -ID $CHG -InputData $UpdateChangeRequestDetails -Verbose
```
![image](https://github.com/Snow-Shell/servicenow-powershell/assets/29791934/e09a780a-a32a-4f77-aefa-4bf75fea8617)

Sending a variable cast as a string with "array" objects separated by a comma adds them to the field separated by a line (i.e. unique entries) and no square brackets:
```
[string]$CIs = 'Server1, Server2'
$UpdateChangeRequestDetails = @{
	u_affected_ci_list = $CIs
}
Update-ServiceNowRecord -ID $CHG -InputData $UpdateChangeRequestDetails -Verbose
```
![image](https://github.com/Snow-Shell/servicenow-powershell/assets/29791934/07176d09-859f-4a1c-b2a4-27ffd13ad10f)

So if the variable is an array:
```
[array]$CIs = @('Server1', 'Server2')
[string]$CIsString = $CIs -join', '
$UpdateChangeRequestDetails = @{
	u_affected_ci_list = $CIsString
}
Update-ServiceNowRecord -ID $CHG -InputData $UpdateChangeRequestDetails -Verbose
```
Works, sending the data without brackets. Unsure what you can do with this info, I can build my script around it, not sure if this matters to anyone else or if I'm just using the function incorrectly.

Cheers
_Fonz

**Comment by gdbarron** [comment]
Hi @tehfonz, this was great info, thanks.

From my research, although SN says it wants json for the payload, that's not applicable to List based fields.  Values for those fields are just comma separated and not arrays which add [ ] when converting to json.  Converting to a string with `[string]$CIs = 'Server1, Server2'` has a value of `Server1, Server2` which is what SN wants.

I'll give some thought to the best way to handle this and update you when I've come up with a solution.

**Comment by gdbarron** [comment]
@tehfonz would you mind testing the fix?

**Comment by tehfonz** [comment]
Hey! So sorry for the long delay. I have finally been able to test this, however I'm not sure how as I have no updated module or code? It looks like this fix was blocked? Am I reading that wrong?

**Comment by gdbarron** [comment]
My turn to apologize for the long delay.  The updated code is in the PR, https://github.com/Snow-Shell/servicenow-powershell/pull/261/files.
