### ISSUE TITLE
Add support for ServiceNow Location field

### ISSUE THREAD

**Issue by mikeclemson** [Snow-Shell/servicenow-powershell#42]
This issue is to add support for a Cmdlet that leverages ServiceNow's Location field.

**Comment by Rick-2CA** [comment]
Hey, Mike.  What kind of support are you after exactly?  There were changes in the past year that would make being able to query the data possible by means of "dot walking" to combine the data while querying other objects, directly via `Get-ServiceNowTableEntry`, or writing the data via Update-`ServiceNowTableEntry`.
