### ISSUE TITLE
Make New-ServiceNowQuery Private

### ISSUE THREAD

**Issue by Rick-2CA** [Snow-Shell/servicenow-powershell#60]
New-ServiceNowQuery is a candidate for being made private in the module.  Looking for feedback from people that are utilizing it for their own functions outside of the module that may be impacted.  Otherwise as far as the module is concerned it's nothing but a support function and can be hidden.

**Comment by thetaylormcrae** [comment]
I'm in favor of keeping it a public function until additional functions can be built around normal use cases. Find that it's easier using Get-ServiceNowTable with New-ServiceNowQuery in most cases. :-)

**Comment by gdbarron** [comment]
Hi @thetaylormcrae.  I would agree.  Would you mind letting me what some of the normal use cases you are referring to are?

**Comment by gdbarron** [comment]
Going to keep public for now
