### ISSUE TITLE
Support using Proxy for ServiceNow URL

### ISSUE THREAD

**Issue by mhackethal** [Snow-Shell/servicenow-powershell#97]
Hi ,

i just want to query the Status i see an already open "fork" #7 for my Question but it was never commited since ~ 1 year.
Any Chance this feature will be inserted ?
I have to provide a Proxy with credentials or at least Parameter DefaultCredentials to Invoke-RestMethod.

Cheers 

Markus

**Comment by Rick-2CA** [comment]
I haven't had to deal with a proxy before.  Is this just a requirement to support `Proxy` on `Invoke-RestMethod` or is there more to it that we'd have to solve for?

**Comment by mhackethal** [comment]
you need to use it on every Invoke-RestMethod or Invoke-Webrequest call. There are some parameters that need to be provided.
- ProxyURL
- either UseDefaultCredentials or provide specific credentials like username/Password that is required to authenticate for the proxy.

I think its a bit tricky to implement this if you dont have any environment using a proxy. I just fixed it for me personal use with a dirty hack ;) but its nothing i can push here.

**Comment by Rick-2CA** [comment]
Would probably be best to force that functionality into `Set-ServiceNowAuth`.  From there it wouldn't be hard to inject it into the right spots for the invoke calls.  Trying to support it on a per command basis as a parameter would be more work and add even more parameters to each command.  I'm hesitant to do more of that.

I'll leave this open and see what can be done.  I've needed to set some time aside for another round of updates anyway.  Busy couple months coming up though.  Thanks for the request.

**Comment by Random206** [comment]
I would love for this feature to be added please.
